apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kmurray-sxmdr-cluster
  region: us-east-1
  version: "1.15"

status:
  endpoint: private

nodeGroups:
  - name: cloudbees-core-masters
    instanceType: r5.xlarge
    minSize: 1
    maxSize: 3
    privateNetworking: true
    labels: {
      partition: masters
    }
    taints: {
      partition: masters:NoSchedule
    }
    iam:
      withAddonPolicies:
        autoScaler: true
        efs: true
    availabilityZones: ["us-east-1a"]

  - name: cloudbees-core-regular
    instanceType: m5.large
    minSize: 1
    maxSize: 3
    privateNetworking: true
    labels: {
      partition: regular-agents
    }
    iam:
      withAddonPolicies:
        autoScaler: true

vpc:
  id: "vpc-03924542ecd936dfd"
  clusterEndpoints:
    publicAccess:  true
    privateAccess: false
  subnets:
    private:
      us-east-1a:
        id: "subnet-0ca83478059ff8bbc"
      us-east-1b:
        id: "subnet-028c4c7840f61debc"
      us-east-1c:
        id: "subnet-0533e417ff03eb82a"
