apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: kmurray-sxmdr-c
  region: us-east-1
  version: "1.15"
status:
  endpoint: private
nodeGroups:
  - name: masters
    instanceType: r5.xlarge
    minSize: 1
    maxSize: 3
    privateNetworking: true
    labels: {
      partition: masters
    }
    taints: {
      partition: masters:NoSchedule
    }
    iam:
      withAddonPolicies:
        autoScaler: true
    availabilityZones: ["us-east-1a"]

  - name: regular
    instanceType: m5.large
    minSize: 1
    maxSize: 3
    privateNetworking: true
    labels: {
      partition: regular-agents
    }
    iam:
      withAddonPolicies:
        autoScaler: true
