apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kmurray-sxmdr
  region: us-east-1
  version: "1.16"
  tags: {
    cb-name: "foobar:cb",
    cb-chocolate: "pretzel:dark"
  }

status:
  endpoint: private

nodeGroups:
  - name: cloudbees-core-masters
    kubeletExtraConfig:
      clusterDNS: []
    instanceType: r5.xlarge
    minSize: 1
    maxSize: 3
    privateNetworking: true
    labels: {
      partition: masters
    }
    taints: {
      partition: masters:NoSchedule
    }
    tags: {
      cb-name: "foobar:cb",
      cb-chocolate: "pretzel:dark"
    }
    iam:
      withAddonPolicies:
        autoScaler: true
#        efs: true
    availabilityZones: ["us-east-1a"]
  - name: cloudbees-core-regular
    kubeletExtraConfig:
      clusterDNS: []
    instanceType: m5.large
    minSize: 1
    maxSize: 3
    privateNetworking: true
    labels: {
      partition: regular-agents
    }
    tags: {
      cb-name: "foobar:cb",
      cb-chocolate: "pretzel:dark"
    }
    iam:
      withAddonPolicies:
        autoScaler: true

vpc:
  id: "REPLACEME-vpcid"
  clusterEndpoints:
    publicAccess:  true
    privateAccess: false
  subnets:
    private:
      us-east-1a:
 #       id: "us-east-1a"
      us-east-1b:
        id: "us-east-1b"
      us-east-1c:
        id: "us-east-1c"
